# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: password
  CLOUD_SQL_DATABASE_NAME: DB
  CLOUD_SQL_CONNECTION_NAME: apadproject19:us-central1:apad
# [END gae_python37_cloudsql_config]